# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-28 17:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_breed_dog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='breed',
            name='name',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='breed',
            name='size',
            field=models.CharField(choices=[('tiny', 'Tiny'), ('small', 'Small'), ('medium', 'Medium'), ('large', 'Large'), ('Tiny', 'tiny'), ('Small', 'small'), ('Medium', 'medium'), ('Large', 'large')], max_length=6),
        ),
        migrations.AlterField(
            model_name='dog',
            name='color',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='dog',
            name='favoriteFood',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='dog',
            name='favoriteToy',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='dog',
            name='gender',
            field=models.CharField(max_length=1),
        ),
        migrations.AlterField(
            model_name='dog',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
